version: '3.8'

services:
  app:
    image: laravel_app:build-${BUILD_NUMBER}
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"

# Webserver:
  # <insert here>

# db:
  # <insert here>