version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_SHORT: ${GIT_COMMIT_SHORT}
        DOCKER_TAG: ${DOCKER_TAG}
    image: laravel_app:${DOCKER_TAG}
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"

# Webserver:
  # <insert here>

# db:
  # <insert here>